// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fvalidator/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInitFValidator struct {
	Creator        string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom          string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	PoolAddress    string   `protobuf:"bytes,3,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	ValAddressList []string `protobuf:"bytes,4,rep,name=valAddressList,proto3" json:"valAddressList,omitempty"`
}

func (m *MsgInitFValidator) Reset()         { *m = MsgInitFValidator{} }
func (m *MsgInitFValidator) String() string { return proto.CompactTextString(m) }
func (*MsgInitFValidator) ProtoMessage()    {}
func (*MsgInitFValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{0}
}
func (m *MsgInitFValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitFValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitFValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitFValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitFValidator.Merge(m, src)
}
func (m *MsgInitFValidator) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitFValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitFValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitFValidator proto.InternalMessageInfo

func (m *MsgInitFValidator) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInitFValidator) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgInitFValidator) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *MsgInitFValidator) GetValAddressList() []string {
	if m != nil {
		return m.ValAddressList
	}
	return nil
}

type MsgInitFValidatorResponse struct {
}

func (m *MsgInitFValidatorResponse) Reset()         { *m = MsgInitFValidatorResponse{} }
func (m *MsgInitFValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitFValidatorResponse) ProtoMessage()    {}
func (*MsgInitFValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{1}
}
func (m *MsgInitFValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitFValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitFValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitFValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitFValidatorResponse.Merge(m, src)
}
func (m *MsgInitFValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitFValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitFValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitFValidatorResponse proto.InternalMessageInfo

type MsgSetCycleSeconds struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Seconds uint64 `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds"`
}

func (m *MsgSetCycleSeconds) Reset()         { *m = MsgSetCycleSeconds{} }
func (m *MsgSetCycleSeconds) String() string { return proto.CompactTextString(m) }
func (*MsgSetCycleSeconds) ProtoMessage()    {}
func (*MsgSetCycleSeconds) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{2}
}
func (m *MsgSetCycleSeconds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCycleSeconds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCycleSeconds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCycleSeconds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCycleSeconds.Merge(m, src)
}
func (m *MsgSetCycleSeconds) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCycleSeconds) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCycleSeconds.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCycleSeconds proto.InternalMessageInfo

func (m *MsgSetCycleSeconds) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetCycleSeconds) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgSetCycleSeconds) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type MsgSetCycleSecondsResponse struct {
}

func (m *MsgSetCycleSecondsResponse) Reset()         { *m = MsgSetCycleSecondsResponse{} }
func (m *MsgSetCycleSecondsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetCycleSecondsResponse) ProtoMessage()    {}
func (*MsgSetCycleSecondsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{3}
}
func (m *MsgSetCycleSecondsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetCycleSecondsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetCycleSecondsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetCycleSecondsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetCycleSecondsResponse.Merge(m, src)
}
func (m *MsgSetCycleSecondsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetCycleSecondsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetCycleSecondsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetCycleSecondsResponse proto.InternalMessageInfo

type MsgSetShuffleSeconds struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Seconds uint64 `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds"`
}

func (m *MsgSetShuffleSeconds) Reset()         { *m = MsgSetShuffleSeconds{} }
func (m *MsgSetShuffleSeconds) String() string { return proto.CompactTextString(m) }
func (*MsgSetShuffleSeconds) ProtoMessage()    {}
func (*MsgSetShuffleSeconds) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{4}
}
func (m *MsgSetShuffleSeconds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetShuffleSeconds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetShuffleSeconds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetShuffleSeconds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetShuffleSeconds.Merge(m, src)
}
func (m *MsgSetShuffleSeconds) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetShuffleSeconds) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetShuffleSeconds.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetShuffleSeconds proto.InternalMessageInfo

func (m *MsgSetShuffleSeconds) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetShuffleSeconds) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgSetShuffleSeconds) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type MsgSetShuffleSecondsResponse struct {
}

func (m *MsgSetShuffleSecondsResponse) Reset()         { *m = MsgSetShuffleSecondsResponse{} }
func (m *MsgSetShuffleSecondsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetShuffleSecondsResponse) ProtoMessage()    {}
func (*MsgSetShuffleSecondsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{5}
}
func (m *MsgSetShuffleSecondsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetShuffleSecondsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetShuffleSecondsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetShuffleSecondsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetShuffleSecondsResponse.Merge(m, src)
}
func (m *MsgSetShuffleSecondsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetShuffleSecondsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetShuffleSecondsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetShuffleSecondsResponse proto.InternalMessageInfo

type MsgAddFValidator struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom       string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	PoolAddress string `protobuf:"bytes,3,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	ValAddress  string `protobuf:"bytes,4,opt,name=valAddress,proto3" json:"valAddress,omitempty"`
}

func (m *MsgAddFValidator) Reset()         { *m = MsgAddFValidator{} }
func (m *MsgAddFValidator) String() string { return proto.CompactTextString(m) }
func (*MsgAddFValidator) ProtoMessage()    {}
func (*MsgAddFValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{6}
}
func (m *MsgAddFValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddFValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddFValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddFValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddFValidator.Merge(m, src)
}
func (m *MsgAddFValidator) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddFValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddFValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddFValidator proto.InternalMessageInfo

func (m *MsgAddFValidator) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddFValidator) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgAddFValidator) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *MsgAddFValidator) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

type MsgAddFValidatorResponse struct {
}

func (m *MsgAddFValidatorResponse) Reset()         { *m = MsgAddFValidatorResponse{} }
func (m *MsgAddFValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddFValidatorResponse) ProtoMessage()    {}
func (*MsgAddFValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{7}
}
func (m *MsgAddFValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddFValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddFValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddFValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddFValidatorResponse.Merge(m, src)
}
func (m *MsgAddFValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddFValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddFValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddFValidatorResponse proto.InternalMessageInfo

type MsgRmFValidator struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom       string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	PoolAddress string `protobuf:"bytes,3,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	OldAddress  string `protobuf:"bytes,4,opt,name=oldAddress,proto3" json:"oldAddress,omitempty"`
	NewAddress  string `protobuf:"bytes,5,opt,name=newAddress,proto3" json:"newAddress,omitempty"`
}

func (m *MsgRmFValidator) Reset()         { *m = MsgRmFValidator{} }
func (m *MsgRmFValidator) String() string { return proto.CompactTextString(m) }
func (*MsgRmFValidator) ProtoMessage()    {}
func (*MsgRmFValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{8}
}
func (m *MsgRmFValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRmFValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRmFValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRmFValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRmFValidator.Merge(m, src)
}
func (m *MsgRmFValidator) XXX_Size() int {
	return m.Size()
}
func (m *MsgRmFValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRmFValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRmFValidator proto.InternalMessageInfo

func (m *MsgRmFValidator) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRmFValidator) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgRmFValidator) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *MsgRmFValidator) GetOldAddress() string {
	if m != nil {
		return m.OldAddress
	}
	return ""
}

func (m *MsgRmFValidator) GetNewAddress() string {
	if m != nil {
		return m.NewAddress
	}
	return ""
}

type MsgRmFValidatorResponse struct {
}

func (m *MsgRmFValidatorResponse) Reset()         { *m = MsgRmFValidatorResponse{} }
func (m *MsgRmFValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRmFValidatorResponse) ProtoMessage()    {}
func (*MsgRmFValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27b98f1fac7fb431, []int{9}
}
func (m *MsgRmFValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRmFValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRmFValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRmFValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRmFValidatorResponse.Merge(m, src)
}
func (m *MsgRmFValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRmFValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRmFValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRmFValidatorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInitFValidator)(nil), "furybase.furybase.fvalidator.MsgInitFValidator")
	proto.RegisterType((*MsgInitFValidatorResponse)(nil), "furybase.furybase.fvalidator.MsgInitFValidatorResponse")
	proto.RegisterType((*MsgSetCycleSeconds)(nil), "furybase.furybase.fvalidator.MsgSetCycleSeconds")
	proto.RegisterType((*MsgSetCycleSecondsResponse)(nil), "furybase.furybase.fvalidator.MsgSetCycleSecondsResponse")
	proto.RegisterType((*MsgSetShuffleSeconds)(nil), "furybase.furybase.fvalidator.MsgSetShuffleSeconds")
	proto.RegisterType((*MsgSetShuffleSecondsResponse)(nil), "furybase.furybase.fvalidator.MsgSetShuffleSecondsResponse")
	proto.RegisterType((*MsgAddFValidator)(nil), "furybase.furybase.fvalidator.MsgAddFValidator")
	proto.RegisterType((*MsgAddFValidatorResponse)(nil), "furybase.furybase.fvalidator.MsgAddFValidatorResponse")
	proto.RegisterType((*MsgRmFValidator)(nil), "furybase.furybase.fvalidator.MsgRmFValidator")
	proto.RegisterType((*MsgRmFValidatorResponse)(nil), "furybase.furybase.fvalidator.MsgRmFValidatorResponse")
}

func init() { proto.RegisterFile("fvalidator/tx.proto", fileDescriptor_27b98f1fac7fb431) }

var fileDescriptor_27b98f1fac7fb431 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x24, 0xa5, 0xea, 0x2b, 0xb4, 0xf4, 0x88, 0x84, 0x7b, 0x44, 0x47, 0x64, 0x09,
	0xd4, 0x05, 0x1b, 0x15, 0xf1, 0x43, 0x6c, 0x2d, 0x53, 0x25, 0xbc, 0x38, 0x12, 0x03, 0x5b, 0x9a,
	0xbb, 0x5c, 0x2d, 0x12, 0x5f, 0xe4, 0xbb, 0xfe, 0x42, 0x62, 0x82, 0x15, 0x89, 0xff, 0x81, 0x7f,
	0x86, 0xb1, 0x23, 0x13, 0x42, 0xc9, 0xc6, 0xce, 0x8e, 0x6c, 0xeb, 0xfc, 0x13, 0x91, 0x7a, 0xc8,
	0xf6, 0xee, 0xbd, 0xef, 0xf7, 0xbd, 0x4f, 0x74, 0xef, 0x62, 0xb8, 0x1b, 0x9d, 0x0d, 0x27, 0x01,
	0x1b, 0x6a, 0x19, 0xb9, 0xfa, 0xc2, 0x99, 0x45, 0x52, 0x4b, 0xdc, 0x53, 0x7a, 0x38, 0x0e, 0x4e,
	0x4e, 0x8f, 0x9d, 0x2c, 0xc8, 0x65, 0xa4, 0x2b, 0xa4, 0x90, 0x89, 0xd0, 0x8d, 0xa3, 0xd4, 0x63,
	0x7f, 0x41, 0xb0, 0xe3, 0x29, 0x71, 0x14, 0x06, 0xda, 0x7f, 0x6b, 0xb4, 0xd8, 0x82, 0xf5, 0x51,
	0xc4, 0xe3, 0xd0, 0x42, 0x7d, 0xb4, 0xb7, 0xe1, 0x9b, 0x23, 0xee, 0xc2, 0x1a, 0xe3, 0xa1, 0x9c,
	0x5a, 0x37, 0x92, 0x7c, 0x7a, 0xc0, 0x7d, 0xd8, 0x9c, 0x49, 0x39, 0x39, 0x60, 0x2c, 0xe2, 0x4a,
	0x59, 0xed, 0xa4, 0x56, 0x4c, 0xe1, 0x47, 0xb0, 0x75, 0x36, 0x34, 0xa7, 0x37, 0x81, 0xd2, 0x56,
	0xa7, 0xdf, 0xde, 0xdb, 0xf0, 0x2b, 0x59, 0xfb, 0x3e, 0xec, 0xd6, 0x70, 0x7c, 0xae, 0x66, 0x32,
	0x54, 0xdc, 0x7e, 0x0f, 0xd8, 0x53, 0x62, 0xc0, 0xf5, 0xeb, 0xcb, 0xd1, 0x84, 0x0f, 0xf8, 0x48,
	0x86, 0x4c, 0x35, 0x86, 0x7d, 0x08, 0xeb, 0x2a, 0xb5, 0x26, 0xa0, 0x9d, 0xc3, 0xcd, 0xdf, 0x3f,
	0x1f, 0x98, 0x94, 0x6f, 0x02, 0xbb, 0x07, 0xa4, 0x3e, 0x2c, 0x43, 0x99, 0x42, 0x37, 0xad, 0x0e,
	0x4e, 0x4e, 0xc7, 0xe3, 0x95, 0xc3, 0x50, 0xe8, 0xfd, 0x6b, 0x5c, 0x86, 0xf3, 0x19, 0xc1, 0x1d,
	0x4f, 0x89, 0x03, 0xc6, 0x56, 0x7a, 0x8b, 0x14, 0x20, 0xbf, 0x2f, 0xab, 0x93, 0x08, 0x0a, 0x19,
	0x9b, 0x80, 0x55, 0xa5, 0xc8, 0x10, 0xbf, 0x21, 0xd8, 0xf6, 0x94, 0xf0, 0xa7, 0xab, 0x26, 0x94,
	0x13, 0x56, 0x21, 0xcc, 0x33, 0x71, 0x3d, 0xe4, 0xe7, 0xa6, 0xbe, 0x96, 0xd6, 0xf3, 0x8c, 0xbd,
	0x0b, 0xf7, 0x2a, 0x90, 0xe6, 0x07, 0xec, 0xff, 0xe9, 0x40, 0xdb, 0x53, 0x02, 0x7f, 0x80, 0xad,
	0xca, 0x73, 0x71, 0x9d, 0xff, 0xbd, 0x3c, 0xa7, 0xb6, 0xd0, 0xe4, 0x45, 0x43, 0x83, 0x61, 0xc0,
	0x1f, 0x61, 0xbb, 0xba, 0xfe, 0x4f, 0x96, 0xf6, 0xaa, 0x38, 0xc8, 0xcb, 0xa6, 0x8e, 0x6c, 0xfc,
	0x27, 0x04, 0x3b, 0xf5, 0x9d, 0xdf, 0xbf, 0x4e, 0xbf, 0xb2, 0x87, 0xbc, 0x6a, 0xee, 0xc9, 0x28,
	0xce, 0xe1, 0x76, 0x79, 0xd1, 0x9d, 0xa5, 0xcd, 0x4a, 0x7a, 0xf2, 0xbc, 0x99, 0x3e, 0x1b, 0xac,
	0xe1, 0x56, 0x69, 0x7d, 0x1f, 0x2f, 0xed, 0x53, 0x94, 0x93, 0x67, 0x8d, 0xe4, 0x66, 0xea, 0xe1,
	0xd1, 0xf7, 0x39, 0x45, 0x57, 0x73, 0x8a, 0x7e, 0xcd, 0x29, 0xfa, 0xba, 0xa0, 0xad, 0xab, 0x05,
	0x6d, 0xfd, 0x58, 0xd0, 0xd6, 0x3b, 0x57, 0x04, 0x3a, 0x6e, 0x32, 0x92, 0x53, 0xd7, 0x74, 0xcc,
	0x83, 0x0b, 0xb7, 0xf8, 0x91, 0xb8, 0x9c, 0x71, 0x75, 0x7c, 0x33, 0xf9, 0xd3, 0x7f, 0xfa, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x08, 0x2d, 0x05, 0x1f, 0x3f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	InitFValidator(ctx context.Context, in *MsgInitFValidator, opts ...grpc.CallOption) (*MsgInitFValidatorResponse, error)
	SetCycleSeconds(ctx context.Context, in *MsgSetCycleSeconds, opts ...grpc.CallOption) (*MsgSetCycleSecondsResponse, error)
	SetShuffleSeconds(ctx context.Context, in *MsgSetShuffleSeconds, opts ...grpc.CallOption) (*MsgSetShuffleSecondsResponse, error)
	AddFValidator(ctx context.Context, in *MsgAddFValidator, opts ...grpc.CallOption) (*MsgAddFValidatorResponse, error)
	RmFValidator(ctx context.Context, in *MsgRmFValidator, opts ...grpc.CallOption) (*MsgRmFValidatorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InitFValidator(ctx context.Context, in *MsgInitFValidator, opts ...grpc.CallOption) (*MsgInitFValidatorResponse, error) {
	out := new(MsgInitFValidatorResponse)
	err := c.cc.Invoke(ctx, "/furybase.furybase.fvalidator.Msg/InitFValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetCycleSeconds(ctx context.Context, in *MsgSetCycleSeconds, opts ...grpc.CallOption) (*MsgSetCycleSecondsResponse, error) {
	out := new(MsgSetCycleSecondsResponse)
	err := c.cc.Invoke(ctx, "/furybase.furybase.fvalidator.Msg/SetCycleSeconds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetShuffleSeconds(ctx context.Context, in *MsgSetShuffleSeconds, opts ...grpc.CallOption) (*MsgSetShuffleSecondsResponse, error) {
	out := new(MsgSetShuffleSecondsResponse)
	err := c.cc.Invoke(ctx, "/furybase.furybase.fvalidator.Msg/SetShuffleSeconds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddFValidator(ctx context.Context, in *MsgAddFValidator, opts ...grpc.CallOption) (*MsgAddFValidatorResponse, error) {
	out := new(MsgAddFValidatorResponse)
	err := c.cc.Invoke(ctx, "/furybase.furybase.fvalidator.Msg/AddFValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RmFValidator(ctx context.Context, in *MsgRmFValidator, opts ...grpc.CallOption) (*MsgRmFValidatorResponse, error) {
	out := new(MsgRmFValidatorResponse)
	err := c.cc.Invoke(ctx, "/furybase.furybase.fvalidator.Msg/RmFValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	InitFValidator(context.Context, *MsgInitFValidator) (*MsgInitFValidatorResponse, error)
	SetCycleSeconds(context.Context, *MsgSetCycleSeconds) (*MsgSetCycleSecondsResponse, error)
	SetShuffleSeconds(context.Context, *MsgSetShuffleSeconds) (*MsgSetShuffleSecondsResponse, error)
	AddFValidator(context.Context, *MsgAddFValidator) (*MsgAddFValidatorResponse, error)
	RmFValidator(context.Context, *MsgRmFValidator) (*MsgRmFValidatorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) InitFValidator(ctx context.Context, req *MsgInitFValidator) (*MsgInitFValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitFValidator not implemented")
}
func (*UnimplementedMsgServer) SetCycleSeconds(ctx context.Context, req *MsgSetCycleSeconds) (*MsgSetCycleSecondsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCycleSeconds not implemented")
}
func (*UnimplementedMsgServer) SetShuffleSeconds(ctx context.Context, req *MsgSetShuffleSeconds) (*MsgSetShuffleSecondsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetShuffleSeconds not implemented")
}
func (*UnimplementedMsgServer) AddFValidator(ctx context.Context, req *MsgAddFValidator) (*MsgAddFValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFValidator not implemented")
}
func (*UnimplementedMsgServer) RmFValidator(ctx context.Context, req *MsgRmFValidator) (*MsgRmFValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RmFValidator not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_InitFValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitFValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitFValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furybase.furybase.fvalidator.Msg/InitFValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitFValidator(ctx, req.(*MsgInitFValidator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetCycleSeconds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetCycleSeconds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetCycleSeconds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furybase.furybase.fvalidator.Msg/SetCycleSeconds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetCycleSeconds(ctx, req.(*MsgSetCycleSeconds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetShuffleSeconds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetShuffleSeconds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetShuffleSeconds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furybase.furybase.fvalidator.Msg/SetShuffleSeconds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetShuffleSeconds(ctx, req.(*MsgSetShuffleSeconds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddFValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddFValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddFValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furybase.furybase.fvalidator.Msg/AddFValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddFValidator(ctx, req.(*MsgAddFValidator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RmFValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRmFValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RmFValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/furybase.furybase.fvalidator.Msg/RmFValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RmFValidator(ctx, req.(*MsgRmFValidator))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "furybase.furybase.fvalidator.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitFValidator",
			Handler:    _Msg_InitFValidator_Handler,
		},
		{
			MethodName: "SetCycleSeconds",
			Handler:    _Msg_SetCycleSeconds_Handler,
		},
		{
			MethodName: "SetShuffleSeconds",
			Handler:    _Msg_SetShuffleSeconds_Handler,
		},
		{
			MethodName: "AddFValidator",
			Handler:    _Msg_AddFValidator_Handler,
		},
		{
			MethodName: "RmFValidator",
			Handler:    _Msg_RmFValidator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fvalidator/tx.proto",
}

func (m *MsgInitFValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitFValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitFValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddressList) > 0 {
		for iNdEx := len(m.ValAddressList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ValAddressList[iNdEx])
			copy(dAtA[i:], m.ValAddressList[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddressList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitFValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitFValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitFValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetCycleSeconds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCycleSeconds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCycleSeconds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Seconds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Seconds))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetCycleSecondsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetCycleSecondsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetCycleSecondsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetShuffleSeconds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetShuffleSeconds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetShuffleSeconds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Seconds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Seconds))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetShuffleSecondsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetShuffleSecondsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetShuffleSecondsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddFValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddFValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddFValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddFValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddFValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddFValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRmFValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRmFValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRmFValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewAddress) > 0 {
		i -= len(m.NewAddress)
		copy(dAtA[i:], m.NewAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OldAddress) > 0 {
		i -= len(m.OldAddress)
		copy(dAtA[i:], m.OldAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OldAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRmFValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRmFValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRmFValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInitFValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ValAddressList) > 0 {
		for _, s := range m.ValAddressList {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgInitFValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetCycleSeconds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Seconds != 0 {
		n += 1 + sovTx(uint64(m.Seconds))
	}
	return n
}

func (m *MsgSetCycleSecondsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetShuffleSeconds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Seconds != 0 {
		n += 1 + sovTx(uint64(m.Seconds))
	}
	return n
}

func (m *MsgSetShuffleSecondsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddFValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddFValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRmFValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OldAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRmFValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInitFValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitFValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitFValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddressList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddressList = append(m.ValAddressList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitFValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitFValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitFValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCycleSeconds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCycleSeconds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCycleSeconds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			m.Seconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetCycleSecondsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetCycleSecondsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetCycleSecondsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetShuffleSeconds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetShuffleSeconds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetShuffleSeconds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			m.Seconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetShuffleSecondsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetShuffleSecondsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetShuffleSecondsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddFValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddFValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddFValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddFValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddFValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddFValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRmFValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRmFValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRmFValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRmFValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRmFValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRmFValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
